application: soundcloud-explore
version: tree
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /arbor
  static_dir: arbor
  secure: always

- url: /src
  static_dir: src
  secure: always

- url: /style
  static_dir: style
  secure: always

- url: /js
  static_dir: js
  secure: always

- url: /css
  static_dir: css
  secure: always

- url: /fonts
  static_dir: fonts
  secure: always

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  secure: always

- url: /
  static_files: index.html
  upload: index\.html
  secure: always

- url: /splashpage
  static_files: splashpage.html
  upload: splashpage\.html
  secure: always

- url: /(showstats)
  script: main.app
  login: admin
  secure: always

- url: /(log|getSounds|getFollowings)
  script: main.app
  secure: always

- url: .*
  static_files: index.html
  upload: index\.html
  secure: always

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"